name: Deploy Node.js API

on:
  push:
    branches:
      - master  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Add SSH Key
      run: echo "${{ secrets.EC2_KEY }}" > ec2-key.pem && chmod 400 ec2-key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
          cd /path/to/your/app
          git pull origin master  # Pull latest code
          npm install  # Install dependencies
          pm2 restart all  # Restart the app using PM2
        EOF
